### ISSUE TITLE
Problem with loading GL functions

### ISSUE THREAD

**Issue by DeafMan1983** [AshleighAdams/dotnet-webgl-sample#1]
Hello nice job with WASM!

But I tried with simple white triangle and it can't see in my code like this your code with I use white Triangle 

```
		uint vaoID = 0;
		GL.glGenVertexArrays(1,&vaoID);

		uint vboID = 0;
		GL.glGenBuffers(1, &vboID);

		GL.glBindVertexArray(vaoID);
		GL.glBindBuffer(BufferTargetARB.ArrayBuffer, vboID);

		float[] vertices = {
			 0.0f,  0.5f, 0.0f,
		     0.5f, -0.5f, 0.0f,
			-0.5f, -0.5f, 0.0f
		};

		fixed (float* vertices_ptr = &vertices[0])
		{
			GL.glBufferData(BufferTargetARB.ArrayBuffer, vertices.Length * sizeof(float), vertices_ptr, BufferUsageARB.StaticDraw);
		}

		int stride = 3 * sizeof(float);
		GL.glVertexAttribPointer(0, 3, VertexAttribPointerType.Float, false, stride, (void*)0);
		GL.glEnableVertexAttribArray(0);

		GL.glDrawArrays(PrimitiveType.Triangles, 0, 3);	
```

Add lines asssssssssfter `GL.LoadAllFunctions(EGL.GetProcAddress);`

Than I type dotnet build -c Release and dotnet run -c Release and I open chrome and it doesn't see triangle :(

![image](https://user-images.githubusercontent.com/57066679/168846396-cde43bda-a679-41c6-bc4e-33e249ff25af.png)

How do I fix? I thought WASM has not problem with OpenGLES.

**Comment by AshleighAdams** [comment]
Just to check, have you set a shader to render your verts? It would be helpful if you upload the solution in full so I can take a look.

**Comment by DeafMan1983** [comment]
Hello @AshleighAdams  sorry I am busy for trying to resolve with WASM-Test like you made but It is really hard to find. I thought MyRuntime() should with GL function, correct or wrong?

Check my repository under Github [DeafMan1983/Wasm-Test](https://github.com/DeafMan1983/Wasm-Test)

Thanks!

**Comment by AshleighAdams** [comment]
I took a quick  look, and it looks like you're doing the rendering once on load, which is then cleared in `Frame()` here: https://github.com/DeafMan1983/Wasm-Test/blob/f49e8bd439842ac1c2ad705ca5c55d2a2d0c0cda/Program.cs#L130-L135

Frame is where your rendering code should ideally be run, as it's currently set up to be invoked from `requestAnimationFrame()`. Just as a quick test, I commented out the clear invocation, and it resulted in the following:

![image](https://user-images.githubusercontent.com/182589/170545706-5c6dea77-c5a8-487e-b11c-f7f813dcb72c.png)

**Comment by DeafMan1983** [comment]
Thank you for explanation! I have tried triangle with shader = ok
But without shader than it can't show white triangle if you work without shader. so sad. I know OpenGL 3.3 uses without shader means it shows only white shapes... 

Thank you for helping me! Now I got triangle on wasm :)
![image](https://user-images.githubusercontent.com/57066679/170551357-13791121-b473-4e5f-bfb4-a8087d07d84e.png)
